baseURL = "https://pietroglyph.github.io"
title = "declan on the interwebs"
copyright = "&copy; 2021. Licensed under the GNU Free Documentation License."

languageCode = "en-US"
defaultContentLanguage = "en"

paginate = 100
theme = "papermod"

enableInlineShortcodes = true
enableRobotsTXT = true
enableEmoji = true

[languages.en]
languageName = "English"
weight = 1

[outputs]
home = [ "HTML", "RSS", "JSON" ]

[params]
description = "Declan's portfolio"
author = "Declan Freeman-Gleason"
ShowToc = true

  [params.homeInfoParams]
  Title = "Declan's portfolio"
  Content = """
I'm Declan. I like math and systems-level programming. I've written controls, state estimation, trajectory generation, visual SLAM, and factor graph optimization code. You can find some of my projects below.
"""

  [[params.socialIcons]]
  name = "github"
  url = "https://github.com/pietroglyph"

  [[params.socialIcons]]
  name = "RSS"
  url = "index.xml"

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[markup.goldmark.renderer]
unsafe = true
